# Generated by Django 4.1.3 on 2022-11-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_wallet_id_alter_service_id_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.URLField(default='example'),
            preserve_default=False,
        ),
    ]
