# Generated by Django 4.1.3 on 2022-11-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_order_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sampleURL',
            field=models.URLField(default='example'),
            preserve_default=False,
        ),
    ]
