# Generated by Django 4.1.3 on 2022-11-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Order',
                'verbose_name_plural': 'Pending Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.order',),
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='paidDate',
            field=models.DateTimeField(null=True),
        ),
    ]
